preset: recommended

risky: true

enabled:
  - strict
  - align_equals
  - newline_after_open_tag
  - long_array_syntax
  - unalign_double_arrow

disabled:
  - unalign_equals
  - no_empty_phpdoc

finder:
  exclude:
    - "src/Model"
    - "src/Interfaces"
